### ISSUE TITLE
CONFUSED

### ISSUE THREAD

**Issue by worstone629** [bkendzior/cowfiles#14]
CAN I MAKE NEW ASCII ART AND ADD IN COWSAY

**Comment by bkendzior** [comment]
Feel free to add the art in a personal fork of the project and request a merge via PR!

**Comment by ricksbrown** [comment]
If I may chime in...

Cowsay takes a `-f` command line argument which allows you to specify your own ascii art to use instead of the default cow. Note that a cowfile is not plain ascii art, it is a cowfile which technically is a perl "heredoc".

So you can do this:

```bash
cowsay -f path/to/cowfiles/mooghidjirah.cow Moo!
```

Here's what the documentation says:
>The -f option specifies a particular cow picture file (''cowfile'') to use. If the cowfile spec contains '/' then it will be interpreted as a path relative to the current directory. Otherwise, cowsay will search the path specified in the COWPATH environment variable.

So, to tweak the above example, you could also use the COWPATH like so:

```bash
export COWPATH=/path/to/cowfiles
cowsay -f mooghidjirah Moo!
```
